package com.affise.attribution.parameters

object Parameters {
    const val AFFISE_EVENT_ID = "affise_event_id"
    const val AFFISE_EVENT_NAME = "affise_event_name" //todo hold
    const val AFFISE_EVENT_CATEGORY = "affise_event_category"
    const val AFFISE_EVENT_TIMESTAMP = "affise_event_timestamp"
    const val AFFISE_EVENT_FIRST_FOR_USER = "affise_event_first_for_user"
    const val AFFISE_EVENT_USER_DATA = "affise_event_user_data"
    const val AFFISE_EVENT_DATA = "affise_event_data"
    const val AFFISE_PARAMETERS = "affise_parameters"

    const val AFFISE_APP_ID = "affise_app_id"
    const val AFFISE_PKG_APP_NAME = "affise_pkg_app_name"
    const val AFF_APP_NAME_DASHBOARD = "affise_app_name_dashboard" //todo abort
    const val APP_VERSION = "app_version"
    const val APP_VERSION_RAW = "app_version_raw"
    const val STORE = "store"
    const val TRACKER_TOKEN = "tracker_token" //todo hold
    const val TRACKER_NAME = "tracker_name" //todo hold
    const val FIRST_TRACKER_TOKEN = "first_tracker_token" //todo hold
    const val FIRST_TRACKER_NAME = "first_tracker_name" //todo hold
    const val LAST_TRACKER_TOKEN = "last_tracker_token" //todo hold
    const val LAST_TRACKER_NAME = "last_tracker_name" //todo hold
    const val OUTDATED_TRACKER_TOKEN = "outdated_tracker_token" //todo hold
    const val INSTALLED_TIME = "installed_time"
    const val FIRST_OPEN_TIME = "first_open_time"
    const val INSTALLED_HOUR = "installed_hour"
    const val FIRST_OPEN_HOUR = "first_open_hour"
    const val INSTALL_FIRST_EVENT = "install_first_event"
    const val INSTALL_BEGIN_TIME = "install_begin_time"
    const val INSTALL_FINISH_TIME = "install_finish_time"
    const val REFERRER_INSTALL_VERSION = "referrer_install_version"
    const val REFERRAL_TIME = "referral_time"
    const val REFERRER_CLICK_TIME = "referrer_click_time"
    const val REFERRER_CLICK_TIME_SERVER = "referrer_click_time_server"
    const val REFERRER_GOOGLE_PLAY_INSTANT = "referrer_google_play_instant"
    const val CREATED_TIME = "created_time"
    const val CREATED_TIME_MILLI = "created_time_milli"
    const val CREATED_TIME_HOUR = "created_time_hour"
    const val UNINSTALL_TIME = "uninstall_time" //todo research
    const val REINSTALL_TIME = "reinstall_time" //todo research
    const val LAST_SESSION_TIME = "last_session_time"
    const val CPU_TYPE = "cpu_type"
    const val HARDWARE_NAME = "hardware_name"
    const val DEVICE_MANUFACTURER = "device_manufacturer"
    const val DEEPLINK_CLICK = "deeplink_click" // todo
    const val DEVICE_ATLAS_ID = "device_atlas_id" // todo
    const val AFFISE_DEVICE_ID = "affise_device_id"
    const val AFFISE_ALT_DEVICE_ID = "affise_alt_device_id"
    const val ANDROID_ID = "android_id"
    const val ANDROID_ID_MD5 = "android_id_md5"
    const val REFTOKEN = "reftoken"
    const val REFTOKENS = "reftokens"
    const val REFERRER = "referrer"
    const val USER_AGENT = "user_agent"
    const val MCCODE = "mccode"
    const val MNCODE = "mncode"
    const val REGION = "region"
    const val COUNTRY = "country"
    const val LANGUAGE = "language"
    const val DEVICE_NAME = "device_name"
    const val DEVICE_TYPE = "device_type"
    const val OS_NAME = "os_name"
    const val PLATFORM = "platform"
    const val SDK_PLATFORM = "sdk_platform"
    const val API_LEVEL_OS = "api_level_os"
    const val AFFISE_SDK_VERSION = "affise_sdk_version"
    const val OS_VERSION = "os_version"
    const val RANDOM_USER_ID = "random_user_id"
    const val AFFISE_SDK_POS = "affise_sdk_pos"
    const val TIMEZONE_DEV = "timezone_dev"
    const val AFFISE_EVENT_TOKEN = "affise_event_token" //todo hold
    const val LAST_TIME_SESSION = "last_time_session"
    const val TIME_SESSION = "time_session"
    const val AFFISE_SESSION_COUNT = "affise_session_count"
    const val LIFETIME_SESSION_COUNT = "lifetime_session_count" //todo
    const val AFFISE_DEEPLINK = "affise_deeplink"
    const val AFFISE_PART_PARAM_NAME = "affise_part_param_name"
    const val AFFISE_PART_PARAM_NAME_TOKEN = "affise_part_param_name_token"
    const val AFFISE_APP_TOKEN = "affise_app_token"
    const val LABEL = "label" //todo hold
    const val AFFISE_SDK_SECRET_ID = "affise_sdk_secret_id"
    const val UUID = "uuid"
    const val AFFISE_APP_OPENED = "affise_app_opened"
    const val PUSHTOKEN = "pushtoken"
    const val AFFISE_EVENTS_COUNT = "affise_events_count"
    const val AFFISE_SDK_EVENTS_COUNT = "affise_sdk_events_count"
    const val AFFISE_METRICS_EVENTS_COUNT = "affise_metrics_events_count"
    const val AFFISE_INTERNAL_EVENTS_COUNT = "affise_internal_events_count"
}