package com.affise.attribution.parameters

enum class ProviderType(val provider: String) {
    AFFISE_APP_ID("affise_app_id"),
    AFFISE_PKG_APP_NAME("affise_pkg_app_name"),
    AFF_APP_NAME_DASHBOARD("affise_app_name_dashboard"),
    APP_VERSION("app_version"),
    APP_VERSION_RAW("app_version_raw"),
    STORE("store"),
    TRACKER_TOKEN("tracker_token"),
    TRACKER_NAME("tracker_name"),
    FIRST_TRACKER_TOKEN("first_tracker_token"),
    FIRST_TRACKER_NAME("first_tracker_name"),
    LAST_TRACKER_TOKEN("last_tracker_token"),
    LAST_TRACKER_NAME("last_tracker_name"),
    OUTDATED_TRACKER_TOKEN("outdated_tracker_token"),
    INSTALLED_TIME("installed_time"),
    FIRST_OPEN_TIME("first_open_time"),
    INSTALLED_HOUR("installed_hour"),
    FIRST_OPEN_HOUR("first_open_hour"),
    INSTALL_FIRST_EVENT("install_first_event"),
    INSTALL_BEGIN_TIME("install_begin_time"),
    INSTALL_FINISH_TIME("install_finish_time"),
    REFERRER_INSTALL_VERSION("referrer_install_version"),
    REFERRAL_TIME("referral_time"),
    REFERRER_CLICK_TIME("referrer_click_time"),
    REFERRER_CLICK_TIME_SERVER("referrer_click_time_server"),
    REFERRER_GOOGLE_PLAY_INSTANT("referrer_google_play_instant"),
    CREATED_TIME("created_time"),
    CREATED_TIME_MILLI("created_time_milli"),
    CREATED_TIME_HOUR("created_time_hour"),
    UNINSTALL_TIME("uninstall_time"),
    REINSTALL_TIME("reinstall_time"),
    LAST_SESSION_TIME("last_session_time"),
    CPU_TYPE("cpu_type"),
    HARDWARE_NAME("hardware_name"),
    DEVICE_MANUFACTURER("device_manufacturer"),
    DEEPLINK_CLICK("deeplink_click"),
    DEVICE_ATLAS_ID("device_atlas_id"),
    AFFISE_DEVICE_ID("affise_device_id"),
    AFFISE_ALT_DEVICE_ID("affise_alt_device_id"),
    ANDROID_ID("android_id"),
    ANDROID_ID_MD5("android_id_md5"),
    REFTOKEN("reftoken"),
    REFTOKENS("reftokens"),
    REFERRER("referrer"),
    USER_AGENT("user_agent"),
    MCCODE("mccode"),
    MNCODE("mncode"),
    REGION("region"),
    COUNTRY("country"),
    LANGUAGE("language"),
    DEVICE_NAME("device_name"),
    DEVICE_TYPE("device_type"),
    OS_NAME("os_name"),
    PLATFORM("platform"),
    SDK_PLATFORM("sdk_platform"),
    API_LEVEL_OS("api_level_os"),
    AFFISE_SDK_VERSION("affise_sdk_version"),
    OS_VERSION("os_version"),
    RANDOM_USER_ID("random_user_id"),
    AFFISE_SDK_POS("affise_sdk_pos"),
    TIMEZONE_DEV("timezone_dev"),
    AFFISE_EVENT_NAME("affise_event_name"),
    AFFISE_EVENT_TOKEN("affise_event_token"),
    LAST_TIME_SESSION("last_time_session"),
    TIME_SESSION("time_session"),
    AFFISE_SESSION_COUNT("affise_session_count"),
    LIFETIME_SESSION_COUNT("lifetime_session_count"),
    AFFISE_DEEPLINK("affise_deeplink"),
    AFFISE_PART_PARAM_NAME("affise_part_param_name"),
    AFFISE_PART_PARAM_NAME_TOKEN("affise_part_param_name_token"),
    AFFISE_APP_TOKEN("affise_app_token"),
    LABEL("label"),
    AFFISE_SDK_SECRET_ID("affise_sdk_secret_id"),
    UUID("uuid"),
    AFFISE_APP_OPENED("affise_app_opened"),
    PUSHTOKEN("pushtoken"),
    AFFISE_EVENTS_COUNT("affise_events_count"),
    AFFISE_SDK_EVENTS_COUNT("affise_sdk_events_count"),
    AFFISE_METRICS_EVENTS_COUNT("affise_metrics_events_count"),
    AFFISE_INTERNAL_EVENTS_COUNT("affise_internal_events_count"),
    IS_ROOTED("is_rooted"),
    IS_EMULATOR("is_emulator"),

    // advertising
    GAID_ADID("gaid_adid"),
    GAID_ADID_MD5("gaid_adid_md5"),
    OAID("oaid"),
    OAID_MD5("oaid_md5"),
    ADID("adid"),
    ALTSTR_ADID("altstr_adid"),
    FIREOS_ADID("fireos_adid"),
    COLOROS_ADID("coloros_adid"),

    // network
    MAC_SHA1("mac_sha1"),
    MAC_MD5("mac_md5"),
    CONNECTION_TYPE("connection_type"),
    PROXY_IP_ADDRESS("proxy_ip_address"),

    // phone
    NETWORK_TYPE("network_type"),
    ISP("isp"),
    ;

    companion object {
        @JvmStatic
        fun from(name: String?): ProviderType? = name?.let { value ->
            ProviderType.values().firstOrNull { it.provider == value }
        }
    }
}